### PR TITLE
Update cer.js to reflect changes in faculty

### PR DESCRIPTION
**Pull request by aakash1104**

### CODE REVIEW

**Comment by amyjko** [comment]
Thank you Akash! Two notes:

* Is Joël able to advise doctoral students? At some institutions, teaching-track faculty cannot, and this is a list of potential advisors. Just double-checking.
* If Joël can advise, can you revise this pull to keep the list alphabetized?

**Comment by aakash1104** [comment]
Yes, he can advice PhD students! :) I'll go revise the PR right now

**Comment by aakash1104** [comment]
Updated! :)

**Comment by amyjko** [comment]
Changes are live.

**Pull request merged**
